for o in `ls -d Lefse_${i}`
do 
/public3/Pipeline/Amplicon/version6.0/lefse/format_input.py /public2/Users/dengdy/cmDNA/new_group_file/Lefse_${i}/${o}/lefse_input_form_group.xls /public2/Users/dengdy/cmDNA/new_group_file/Lefse_${i}/${o}/hmp_aerobiosis_small.in -c 1 -o 1000000 -u 2
/public3/Pipeline/Amplicon/version6.0/lefse/run_lefse.py /public2/Users/dengdy/cmDNA/new_group_file/Lefse_${i}/${o}/hmp_aerobiosis_small.in /public2/Users/dengdy/cmDNA/new_group_file/Lefse_${i}/${o}/hmp_aerobiosis_small.res
/public2/Users/hongwj/software/anaconda/bin/python3.7 /public3/Pipeline/Amplicon/version6.0/lefse.top.py /public2/Users/dengdy/cmDNA/new_group_file/Lefse_${i}/${o}/hmp_aerobiosis_small.res /public2/Users/dengdy/cmDNA/new_group_file/Lefse_${i}/${o}/hmp_aerobiosis_small.res.top 10
/public3/Pipeline/Amplicon/version6.0/lefse/plot_cladogram.py /public2/Users/dengdy/cmDNA/new_group_file/Lefse_${i}/${o}/hmp_aerobiosis_small.res.top /public2/Users/dengdy/cmDNA/new_group_file/Lefse_${i}/${o}/Top.LEfSe.cladogram.png --format png --dpi 300 --labeled_start_lev 0 --labeled_stop_lev 7 --abrv_start_lev 3 --abrv_stop_lev 7
/public3/Pipeline/Amplicon/version6.0/lefse/plot_cladogram.py /public2/Users/dengdy/cmDNA/new_group_file/Lefse_${i}/${o}/hmp_aerobiosis_small.res.top /public2/Users/dengdy/cmDNA/new_group_file/Lefse_${i}/${o}/Top.LEfSe.cladogram.svg --format svg --labeled_start_lev 0 --labeled_stop_lev 7 --abrv_start_lev 3 --abrv_stop_lev 7
/public3/Pipeline/Amplicon/version6.0/lefse/plot_res.py /public2/Users/dengdy/cmDNA/new_group_file/Lefse_${i}/${o}/hmp_aerobiosis_small.res.top /public2/Users/dengdy/cmDNA/new_group_file/Lefse_${i}/${o}/Top.LEfSe.bar.png --dpi 300 
/public3/Pipeline/Amplicon/version6.0/lefse/plot_res.py  /public2/Users/dengdy/cmDNA/new_group_file/Lefse_${i}/${o}/hmp_aerobiosis_small.res.top /public2/Users/dengdy/cmDNA/new_group_file/Lefse_${i}/${o}/Top.LEfSe.bar.svg --format svg 
/public3/Pipeline/Amplicon/version6.0/lefse/plot_cladogram.py /public2/Users/dengdy/cmDNA/new_group_file/Lefse_${i}/${o}/hmp_aerobiosis_small.res /public2/Users/dengdy/cmDNA/new_group_file/Lefse_${i}/${o}/All.LEfSe.cladogram.png --format png --dpi 300 --labeled_start_lev 0 --labeled_stop_lev 7 --abrv_start_lev 3 --abrv_stop_lev 7
/public3/Pipeline/Amplicon/version6.0/lefse/plot_cladogram.py /public2/Users/dengdy/cmDNA/new_group_file/Lefse_${i}/${o}/hmp_aerobiosis_small.res /public2/Users/dengdy/cmDNA/new_group_file/Lefse_${i}/${o}/All.LEfSe.cladogram.svg --format svg --labeled_start_lev 0 --labeled_stop_lev 7 --abrv_start_lev 3 --abrv_stop_lev 7
/public3/Pipeline/Amplicon/version6.0/lefse/plot_res.py /public2/Users/dengdy/cmDNA/new_group_file/Lefse_${i}/${o}/hmp_aerobiosis_small.res /public2/Users/dengdy/cmDNA/new_group_file/Lefse_${i}/${o}/All.LEfSe.bar.png --dpi 300 
/public3/Pipeline/Amplicon/version6.0/lefse/plot_res.py  /public2/Users/dengdy/cmDNA/new_group_file/Lefse_${i}/${o}/hmp_aerobiosis_small.res /public2/Users/dengdy/cmDNA/new_group_file/Lefse_${i}/${o}/All.LEfSe.bar.svg --format svg
done
